name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
     - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Date
      run: date > version
    - name: Env
      run: env
    - name: Version
      run: echo ${GITHUB_REF} >> version; cat version
    - name: Build
      run: cargo build --release --verbose
    - name: Inspect
      run: file ./target/release/ci
    - name: Run
      run: ./target/release/ci
    - name: Run tests
      run: cargo test --verbose -- --nocapture
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ci
        path: ./target/release/ci
        retention-days: 90
    - name: S1
      run: mkdir d
    - name: S2
      run: |
        cd d
	echo derp > derp.html
	cd ..
    - name: S3
      uses: actions/upload-artifact@v3
      with:
        name: assets-for-download
	path: d
